/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import com.mycompany.orbitix.controlador.UsuarioControlador;
import javax.swing.JFrame;

/**
 *
 * @author USUARIO
 */
public class VistaRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaRegistro.class.getName());

    /**
     * Creates new form VistaRegistro
     */
  public VistaRegistro() {
    initComponents();

    txtusuario1LOG.setText("Ejemplo: usuario@correo.com");
    txtcontra.setText(""); 

   
    txtusuario1LOG.setForeground(java.awt.Color.GRAY);

   
    txtusuario1LOG.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtusuario1LOG.getText().equals("Ejemplo: usuario@correo.com")) {
                txtusuario1LOG.setText("");
                txtusuario1LOG.setForeground(java.awt.Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtusuario1LOG.getText().isEmpty()) {
                txtusuario1LOG.setForeground(java.awt.Color.GRAY);
                txtusuario1LOG.setText("Ejemplo: usuario@correo.com");
            }
        }
    });
    
    Fondo fondo = new Fondo();
    fondo.setLayout(new java.awt.BorderLayout());
    setContentPane(fondo);

    panelRegistro.setOpaque(false); 
    fondo.add(panelRegistro, java.awt.BorderLayout.CENTER);

    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        labelregistro = new javax.swing.JLabel();
        labelusuarioLOG = new javax.swing.JLabel();
        txtusuario1LOG = new javax.swing.JTextField();
        LOG = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnVolverLOG = new javax.swing.JButton();
        txtcontra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 677));

        panelRegistro.setPreferredSize(new java.awt.Dimension(1360, 677));

        labelregistro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        labelregistro.setForeground(new java.awt.Color(255, 255, 255));
        labelregistro.setText("    CREAR CUENTA");

        labelusuarioLOG.setBackground(new java.awt.Color(153, 0, 255));
        labelusuarioLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelusuarioLOG.setForeground(new java.awt.Color(255, 255, 255));
        labelusuarioLOG.setText("                Usuario");
        labelusuarioLOG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LOG.setBackground(new java.awt.Color(153, 0, 255));
        LOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LOG.setForeground(new java.awt.Color(255, 255, 255));
        LOG.setText("                Contraseña");
        LOG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        btnguardar.setBackground(new java.awt.Color(51, 204, 255));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("GUARDAR Y REGISTRAR");
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        btnVolverLOG.setBackground(new java.awt.Color(51, 204, 255));
        btnVolverLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverLOG.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverLOG.setText("VOLVER");
        btnVolverLOG.addActionListener(this::btnVolverLOGActionPerformed);

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                        .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(762, 762, 762))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelusuarioLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtcontra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusuario1LOG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(LOG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolverLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(428, 428, 428))))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelusuarioLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtusuario1LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverLOG))
                .addGap(28, 28, 28)
                .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

    String email = txtusuario1LOG.getText();
    String pass = new String(txtcontra.getPassword()); 
    UsuarioControlador control = new UsuarioControlador();


    if (email.isEmpty() || email.equals("Ejemplo: usuario@correo.com") || pass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

   
    if (!email.contains("@") || !email.contains(".")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El formato del correo es incorrecto.\nDebe ser tipo: usuario@correo.com", 
            "Formato Inválido", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

  
    if (control.login(email, pass) != null) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Este correo ya está registrado.");
        return;
    }

    if (control.registrar(email, pass)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente!");
        
        VistaLogin login = new VistaLogin();
        login.setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Hubo un error al guardar los datos.");
    }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnVolverLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLOGActionPerformed
        VistaInicio inicio = new VistaInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverLOGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOG;
    private javax.swing.JButton btnVolverLOG;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel labelregistro;
    private javax.swing.JLabel labelusuarioLOG;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario1LOG;
    // End of variables declaration//GEN-END:variables
}
