/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author karla
 */
public class VistaAcceso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAcceso.class.getName());

    /**
     * Creates new form VistaAcceso
     */
    public VistaAcceso() {
        initComponents();
        JLabel fondo = new JLabel(new ImageIcon(getClass().getResource("/recursos/fondo_login_orbitix.png")));
    
        fondo.setSize(800, 600); 

        this.getLayeredPane().add(fondo, Integer.valueOf(Integer.MIN_VALUE));
 
        ((JPanel)getContentPane()).setOpaque(false);

   
        this.setSize(800, 600);
        this.setLayout(null); // Ya que quieres usar coordenadas libres
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        lblUsuario.setVisible(false);       // Cambia estos nombres por los 
        lblContrasena.setVisible(false);    // nombres de tus variables reales
        txtUsuario.setVisible(false);
        txtContrasena.setVisible(false);
        btnIngresar.setVisible(false);
        btnVolver.setVisible(false);
        

    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBienvenida = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        pnllogin2 = new javax.swing.JPanel();
        pnlCuerpoLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlBienvenida.setOpaque(false);
        pnlBienvenida.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlBienvenida.setLayout(new java.awt.GridBagLayout());

        pnlLogin.setOpaque(false);

        pnllogin2.setBackground(new java.awt.Color(204, 204, 255));
        pnllogin2.setForeground(new java.awt.Color(204, 204, 255));
        pnllogin2.setAutoscrolls(true);
        pnllogin2.setOpaque(false);

        pnlCuerpoLogin.setBackground(new java.awt.Color(153, 153, 153));
        pnlCuerpoLogin.setOpaque(false);

        lblUsuario.setText("Usuario:");
        lblUsuario.setOpaque(true);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblContrasena.setText("Contraseña:");
        lblContrasena.setOpaque(true);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCuerpoLoginLayout = new javax.swing.GroupLayout(pnlCuerpoLogin);
        pnlCuerpoLogin.setLayout(pnlCuerpoLoginLayout);
        pnlCuerpoLoginLayout.setHorizontalGroup(
            pnlCuerpoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuerpoLoginLayout.createSequentialGroup()
                .addGroup(pnlCuerpoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCuerpoLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCuerpoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContrasena)
                            .addComponent(txtUsuario)
                            .addComponent(lblUsuario)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(pnlCuerpoLoginLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlCuerpoLoginLayout.setVerticalGroup(
            pnlCuerpoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCuerpoLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setText("<<Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnCrearCuenta.setText("Crear Cuenta Nueva");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnllogin2Layout = new javax.swing.GroupLayout(pnllogin2);
        pnllogin2.setLayout(pnllogin2Layout);
        pnllogin2Layout.setHorizontalGroup(
            pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCuenta)
                    .addGroup(pnllogin2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnIniciarSesion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCuerpoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogin2Layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        pnllogin2Layout.setVerticalGroup(
            pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogin2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogin2Layout.createSequentialGroup()
                        .addComponent(pnlCuerpoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogin2Layout.createSequentialGroup()
                        .addComponent(btnIniciarSesion)
                        .addGap(97, 97, 97)))
                .addGroup(pnllogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addGroup(pnllogin2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnCrearCuenta)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnllogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnllogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        pnlBienvenida.add(pnlLogin, gridBagConstraints);

        getContentPane().add(pnlBienvenida, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        lblUsuario.setVisible(true);
        lblContrasena.setVisible(true);
        txtUsuario.setVisible(true);
        txtContrasena.setVisible(true);
        btnIngresar.setVisible(true);
        btnVolver.setVisible(true);

    // Opcional: Ocultar los botones iniciales
        btnIniciarSesion.setVisible(false);
        btnCrearCuenta.setVisible(false);
        CardLayout cl = (CardLayout)(getContentPane().getLayout());
        cl.show(getContentPane(), "pnlLogin");
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        lblUsuario.setVisible(false);
        lblContrasena.setVisible(false);
        txtUsuario.setVisible(false);
        txtContrasena.setVisible(false);
        btnIngresar.setVisible(false);
        btnVolver.setVisible(false);

        // Mostramos los botones principales de nuevo
        btnIniciarSesion.setVisible(true);
        btnCrearCuenta.setVisible(true);
        CardLayout cl = (CardLayout)(this.getLayout()); 
        cl.show(this, "pnlBienvenida");
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaAcceso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBienvenida;
    private javax.swing.JPanel pnlCuerpoLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnllogin2;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
