/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import com.mycompany.orbitix.modelo.Vuelo;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author USUARIO
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private com.mycompany.orbitix.modelo.Usuario usuarioLogueado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    private java.util.List<Vuelo> listaVuelosActuales; 
    private com.mycompany.orbitix.datos.RepositorioArchivos repo = new com.mycompany.orbitix.datos.RepositorioArchivos();

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
     initComponents();
     
    configurarTabla(); 
    llenarCombosDinamicos();
    
    Fondo fondo = new Fondo("/recursos/fondo_VPrincipal_orbitix.png");
    fondo.setLayout(new java.awt.BorderLayout());
    setContentPane(fondo);

    panelPrincipal.setOpaque(false); 
    fondo.add(panelPrincipal, java.awt.BorderLayout.CENTER);

    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelsaludo = new javax.swing.JLabel();
        labeldestino = new javax.swing.JLabel();
        labelvenco1 = new javax.swing.JLabel();
        labelorigen1 = new javax.swing.JLabel();
        btnBuscarVuelos = new javax.swing.JButton();
        cbselorigen = new javax.swing.JComboBox<>();
        cbseldestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        btnSelecComprar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 677));

        panelPrincipal.setBackground(new java.awt.Color(51, 0, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1360, 677));

        labelsaludo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        labelsaludo.setForeground(new java.awt.Color(255, 255, 255));
        labelsaludo.setText("           Hola, Usuario");

        labeldestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeldestino.setForeground(new java.awt.Color(255, 255, 255));
        labeldestino.setText("Destino:");

        labelvenco1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelvenco1.setForeground(new java.awt.Color(255, 255, 255));
        labelvenco1.setText("Vuelos Encontrados");

        labelorigen1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelorigen1.setForeground(new java.awt.Color(255, 255, 255));
        labelorigen1.setText("Origen:");

        btnBuscarVuelos.setBackground(new java.awt.Color(153, 0, 255));
        btnBuscarVuelos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVuelos.setText("BUSCAR VUELOS");
        btnBuscarVuelos.addActionListener(this::btnBuscarVuelosActionPerformed);

        cbselorigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbselorigen.addActionListener(this::cbselorigenActionPerformed);

        cbseldestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbseldestino.addActionListener(this::cbseldestinoActionPerformed);

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVuelos);

        btnSelecComprar.setBackground(new java.awt.Color(153, 0, 255));
        btnSelecComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelecComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecComprar.setText("SELECCIONAR Y COMPRAR");
        btnSelecComprar.addActionListener(this::btnSelecComprarActionPerformed);

        btnSalir.setBackground(new java.awt.Color(153, 0, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnCompras.setBackground(new java.awt.Color(153, 0, 255));
        btnCompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setText("MIS COMPRAS");
        btnCompras.addActionListener(this::btnComprasActionPerformed);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labeldestino)
                                    .addComponent(labelorigen1))
                                .addGap(240, 240, 240)
                                .addComponent(labelvenco1))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarVuelos)
                                    .addComponent(cbseldestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbselorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(btnSelecComprar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(labelsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(197, 197, 197))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                    .addContainerGap(933, Short.MAX_VALUE)
                    .addComponent(btnCompras)
                    .addGap(313, 313, 313)))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnSalir)))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelorigen1)
                    .addComponent(labelvenco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(cbselorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(labeldestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbseldestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnBuscarVuelos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(btnSelecComprar)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPrincipalLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(btnCompras)
                    .addContainerGap(600, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 563, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbselorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbselorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbselorigenActionPerformed

    private void cbseldestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbseldestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbseldestinoActionPerformed

    private void btnBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVuelosActionPerformed
    String origen = cbselorigen.getSelectedItem().toString();
        String destino = cbseldestino.getSelectedItem().toString();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaVuelos.getModel();
        modelo.setRowCount(0); // Limpiar tabla antes de mostrar nuevos resultados

        for (Vuelo v : listaVuelosActuales) {
            if (v.getRuta().getOrigen().equals(origen) && v.getRuta().getDestino().equals(destino)) {
                modelo.addRow(new Object[]{
                    v.getCodigo(),
                    new java.text.SimpleDateFormat("dd/MM/yyyy").format(v.getFecha()),
                    v.getRuta().getOrigen() + " -> " + v.getRuta().getDestino(),
                    "$" + String.format("%.2f", v.getPrecio()),
                    v.getRuta().getDuracionFormateada(), 
                    v.getAsientosDisponibles()
                });
            }
        }
    }//GEN-LAST:event_btnBuscarVuelosActionPerformed

    private void btnSelecComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecComprarActionPerformed
        int fila = tablaVuelos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un vuelo de la tabla primero.");
            return;
        }

        String codigo = tablaVuelos.getValueAt(fila, 0).toString();
        Vuelo seleccionado = null;
        for(Vuelo v : listaVuelosActuales) {
            if(v.getCodigo().equals(codigo)) {
                seleccionado = v;
                break;
            }
        }

        if (seleccionado != null) {
            VistaMapaAsientos mapa = new VistaMapaAsientos(this, seleccionado);
            mapa.setVisible(true);

            List<String> asientos = mapa.getAsientosSeleccionados();

            if (asientos != null && !asientos.isEmpty()) {
                // AHORA LLAMAMOS A LA VENTANA DE REGISTRO Y PAGO
                //VistaPasajerosYPago ventanaPago = new VistaPasajerosYPago(this, seleccionado, asientos, usuarioLogueado);
                //ventanaPago.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSelecComprarActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
    VistaHistorialCompras historial = new VistaHistorialCompras(this, this.usuarioLogueado);
    historial.setVisible(true); 

    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
                                        
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea salir?", "Orbitix - Salir", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }

    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVuelos;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSelecComprar;
    private javax.swing.JComboBox<String> cbseldestino;
    private javax.swing.JComboBox<String> cbselorigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldestino;
    private javax.swing.JLabel labelorigen1;
    private javax.swing.JLabel labelsaludo;
    private javax.swing.JLabel labelvenco1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables
    private void configurarTabla() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                // Añadimos "Duración" entre Precio y Disponibles
                new String [] { "Código", "Fecha", "Ruta", "Precio", "Duración", "Disponibles" }
            ) {
                @Override
                public boolean isCellEditable(int row, int column) { return false; } // Tabla no editable
            };
            tablaVuelos.setModel(modelo);
    }

    private void llenarCombosDinamicos() {
        cbselorigen.removeAllItems();
        cbseldestino.removeAllItems();

        java.util.Set<String> origenes = new java.util.HashSet<>();
        java.util.Set<String> destinos = new java.util.HashSet<>();

        listaVuelosActuales = repo.cargarVuelos(); // Carga desde el archivo

        for (Vuelo v : listaVuelosActuales) {
            origenes.add(v.getRuta().getOrigen());
            destinos.add(v.getRuta().getDestino());
        }

        for (String o : origenes) cbselorigen.addItem(o);
        for (String d : destinos) cbseldestino.addItem(d);
}

}
